
import __ASTRO_IMAGE_IMPORT_10rkwu from "../../assets/minecraft-house-preview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fminecraft-house-python.md";
import __ASTRO_IMAGE_IMPORT_Z1DXvIX from "../../assets/p-arvid-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Farvid-chair.md";
import __ASTRO_IMAGE_IMPORT_Z1vij7I from "../../assets/p-arvid-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Farvid-chair.md";
import __ASTRO_IMAGE_IMPORT_Z1l3vcG from "../../assets/p-halla-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fhalla-shelf.md";
import __ASTRO_IMAGE_IMPORT_Z1cniAr from "../../assets/p-halla-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fhalla-shelf.md";
import __ASTRO_IMAGE_IMPORT_Z2o7jVt from "../../assets/p-monolith-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fmonolith-bench.md";
import __ASTRO_IMAGE_IMPORT_Z1sx1Mc from "../../assets/p-monolith-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fmonolith-bench.md";
import __ASTRO_IMAGE_IMPORT_ZWs7l9 from "../../assets/p-oken-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Foken-stool.md";
import __ASTRO_IMAGE_IMPORT_Zs9Rj3 from "../../assets/p-oken-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Foken-stool.md";
import __ASTRO_IMAGE_IMPORT_Z1WuRh4 from "../../assets/p-plinth-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Flow-plinth-table.md";
import __ASTRO_IMAGE_IMPORT_ZwgclL from "../../assets/p-plinth-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Flow-plinth-table.md";
import __ASTRO_IMAGE_IMPORT_Z1lTHDe from "../../assets/p-tora-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Ftora-desk.md";
import __ASTRO_IMAGE_IMPORT_Z1kV5L2 from "../../assets/p-tora-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Ftora-desk.md";
export default new Map([["../../assets/minecraft-house-preview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fminecraft-house-python.md", __ASTRO_IMAGE_IMPORT_10rkwu], ["../../assets/p-arvid-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Farvid-chair.md", __ASTRO_IMAGE_IMPORT_Z1DXvIX], ["../../assets/p-arvid-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Farvid-chair.md", __ASTRO_IMAGE_IMPORT_Z1vij7I], ["../../assets/p-halla-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fhalla-shelf.md", __ASTRO_IMAGE_IMPORT_Z1l3vcG], ["../../assets/p-halla-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fhalla-shelf.md", __ASTRO_IMAGE_IMPORT_Z1cniAr], ["../../assets/p-monolith-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fmonolith-bench.md", __ASTRO_IMAGE_IMPORT_Z2o7jVt], ["../../assets/p-monolith-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fmonolith-bench.md", __ASTRO_IMAGE_IMPORT_Z1sx1Mc], ["../../assets/p-oken-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Foken-stool.md", __ASTRO_IMAGE_IMPORT_ZWs7l9], ["../../assets/p-oken-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Foken-stool.md", __ASTRO_IMAGE_IMPORT_Zs9Rj3], ["../../assets/p-plinth-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Flow-plinth-table.md", __ASTRO_IMAGE_IMPORT_Z1WuRh4], ["../../assets/p-plinth-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Flow-plinth-table.md", __ASTRO_IMAGE_IMPORT_ZwgclL], ["../../assets/p-tora-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Ftora-desk.md", __ASTRO_IMAGE_IMPORT_Z1lTHDe], ["../../assets/p-tora-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Ftora-desk.md", __ASTRO_IMAGE_IMPORT_Z1kV5L2]]);
		