
import __ASTRO_IMAGE_IMPORT_Z1PYm7T from "../../assets/minecraft-house-preview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fminecraft-house-python.md";
import __ASTRO_IMAGE_IMPORT_coYuH from "../../assets/p-arvid-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Farvid-chair.md";
import __ASTRO_IMAGE_IMPORT_l5c6W from "../../assets/p-arvid-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Farvid-chair.md";
import __ASTRO_IMAGE_IMPORT_vk01Y from "../../assets/p-halla-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fhalla-shelf.md";
import __ASTRO_IMAGE_IMPORT_E0cDe from "../../assets/p-halla-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fhalla-shelf.md";
import __ASTRO_IMAGE_IMPORT_ZCem6Y from "../../assets/p-monolith-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fmonolith-bench.md";
import __ASTRO_IMAGE_IMPORT_ikV2i from "../../assets/p-monolith-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fmonolith-bench.md";
import __ASTRO_IMAGE_IMPORT_Z1RPlO1 from "../../assets/p-oken-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foken-stool.md";
import __ASTRO_IMAGE_IMPORT_Z1nx6LU from "../../assets/p-oken-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foken-stool.md";
import __ASTRO_IMAGE_IMPORT_ZMPnex from "../../assets/p-plinth-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Flow-plinth-table.md";
import __ASTRO_IMAGE_IMPORT_CohFK from "../../assets/p-plinth-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Flow-plinth-table.md";
import __ASTRO_IMAGE_IMPORT_1ynnXF from "../../assets/p-tora-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ftora-desk.md";
import __ASTRO_IMAGE_IMPORT_1zm0PR from "../../assets/p-tora-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ftora-desk.md";
export default new Map([["../../assets/minecraft-house-preview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fminecraft-house-python.md", __ASTRO_IMAGE_IMPORT_Z1PYm7T], ["../../assets/p-arvid-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Farvid-chair.md", __ASTRO_IMAGE_IMPORT_coYuH], ["../../assets/p-arvid-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Farvid-chair.md", __ASTRO_IMAGE_IMPORT_l5c6W], ["../../assets/p-halla-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fhalla-shelf.md", __ASTRO_IMAGE_IMPORT_vk01Y], ["../../assets/p-halla-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fhalla-shelf.md", __ASTRO_IMAGE_IMPORT_E0cDe], ["../../assets/p-monolith-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fmonolith-bench.md", __ASTRO_IMAGE_IMPORT_ZCem6Y], ["../../assets/p-monolith-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fmonolith-bench.md", __ASTRO_IMAGE_IMPORT_ikV2i], ["../../assets/p-oken-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foken-stool.md", __ASTRO_IMAGE_IMPORT_Z1RPlO1], ["../../assets/p-oken-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foken-stool.md", __ASTRO_IMAGE_IMPORT_Z1nx6LU], ["../../assets/p-plinth-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Flow-plinth-table.md", __ASTRO_IMAGE_IMPORT_ZMPnex], ["../../assets/p-plinth-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Flow-plinth-table.md", __ASTRO_IMAGE_IMPORT_CohFK], ["../../assets/p-tora-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ftora-desk.md", __ASTRO_IMAGE_IMPORT_1ynnXF], ["../../assets/p-tora-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ftora-desk.md", __ASTRO_IMAGE_IMPORT_1zm0PR]]);
		